name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
 contents: read
 packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Debug
        run: |
          echo "actor=${{ github.actor }}"
          echo "repo=${{ github.repository }}"
          echo "sha=${{ github.sha }}"
      - name: Cache bazel build
        id: cache-bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ github.sha}}
      - name: Bazel Build
        run: bazel build //...
      - name: Bazel Test
        run: bazel test //...
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag ghcr.io/${{ github.repository }}/my-cpp-image:${{ github.sha }} \
          --tag ghcr.io/${{ github.repository }}/my-cpp-image:latest
      - name: Login GHCR
        if: ${{ github.ref }} == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Upload Docker image
        if: ${{ github.ref }} == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}/my-cpp-image:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/my-cpp-image:latest
